In [1]:
import pandas as pd
import json
import requests
import pprint
from functools import reduce
from keys import fred_key, eia_key

In [2]:
# EIA API Calls
production = requests.get("https://api.eia.gov/series/?api_key="+ eia_key +"&series_id=PET.WCRFPUS2.W")
imports = requests.get("http://api.eia.gov/series/?api_key="+ eia_key +"&series_id=PET.WCRIMUS2.W")
supply = requests.get("http://api.eia.gov/series/?api_key="+ eia_key +"&series_id=PET.WRPUPUS2.W")

print(production.status_code)
print(imports.status_code)
print(supply.status_code)

200
200
200

In [3]:
# FRED API Calls
# The WTI returns price for the week ending Friday. This is the same release dat as the eia data
wti = requests.get("https://api.stlouisfed.org/fred/series/observations?series_id=WCOILWTICO&frequency=wef&api_key="+ 
                   fred_key +"&file_type=json")

# These indicators are only monthly
cpi = requests.get("https://api.stlouisfed.org/fred/series/observations?series_id=CPILFESL&frequency=m&api_key="+ 
                  fred_key +"&file_type=json")
unemployment = requests.get("https://api.stlouisfed.org/fred/series/observations?series_id=UNRATE&frequency=m&api_key="+ 
                  fred_key +"&file_type=json")
personal_consumption_expenditure = requests.get("https://api.stlouisfed.org/fred/series/observations?series_id=PCE&frequency=m&api_key="+ 
                  fred_key +"&file_type=json")

print(wti.status_code)
print(cpi.status_code)
print(unemployment.status_code)
print(personal_consumption_expenditure.status_code)

200
200
200
200

In [4]:
# Convert responses to JSONs
production_json = production.json()
imports_json = imports.json()
supply_json = supply.json()
wti_json = wti.json()
cpi_json = cpi.json()
unemp_json = unemployment.json()
pce_json = personal_consumption_expenditure.json()

In [5]:
# Extract EIA Data
production_series = production_json['series'][0]
imports_series = imports_json['series'][0]
supply_series = supply_json['series'][0]

In [6]:
production_df = pd.DataFrame(production_series['data'])
imports_df = pd.DataFrame(imports_series['data'])
supply_df = pd.DataFrame(supply_series['data'])

In [7]:
# Extract FRED Data
wti_observations = wti_json['observations']
Date = []
Value = []
for observation in wti_observations:
    Date.append(observation['date'])
    Value.append(observation['value'])
wti_df = pd.DataFrame(list(zip(Date,Value)))

In [8]:
cpi_observations = cpi_json['observations']
Date = []
Value = []
for observation in cpi_observations:
    Date.append(observation['date'])
    Value.append(observation['value'])
cpi_df = pd.DataFrame(list(zip(Date,Value)))

In [9]:
unemp_observations = unemp_json['observations']
Date = []
Value = []
for observation in unemp_observations:
    Date.append(observation['date'])
    Value.append(observation['value'])
unemp_df = pd.DataFrame(list(zip(Date,Value)))

In [10]:
pce_observations = pce_json['observations']
Date = []
Value = []
for observation in pce_observations:
    Date.append(observation['date'])
    Value.append(observation['value'])
pce_df = pd.DataFrame(list(zip(Date,Value)))

In [11]:
# Converting to datetime 
production_df.iloc[:,0] = pd.to_datetime(production_df.iloc[:,0],format='%Y%m%d', errors='raise')
imports_df.iloc[:,0] = pd.to_datetime(production_df.iloc[:,0],format='%Y%m%d', errors='raise')
supply_df.iloc[:,0] = pd.to_datetime(production_df.iloc[:,0],format='%Y%m%d', errors='raise')
wti_df.iloc[:,0] = pd.to_datetime(wti_df.iloc[:,0],format='%Y-%m-%d', errors='raise')
cpi_df.iloc[:,0] = pd.to_datetime(cpi_df.iloc[:,0],format='%Y-%m-%d', errors='raise')
unemp_df.iloc[:,0] = pd.to_datetime(unemp_df.iloc[:,0],format='%Y-%m-%d', errors='raise')
pce_df.iloc[:,0] = pd.to_datetime(pce_df.iloc[:,0],format='%Y-%m-%d', errors='raise')

In [12]:
# Rename columns
production_df = production_df.rename(columns = {0:'Date', 1:'Production (thousand barrels per day)'}).sort_values(by='Date').reset_index(drop=True)
imports_df = imports_df.rename(columns = {0:'Date', 1:'Imports (thousand barrels per day)'}).sort_values(by='Date').reset_index(drop=True)
supply_df = supply_df.rename(columns = {0:'Date', 1:'Supply (thousand barrels per day)'}).sort_values(by='Date').reset_index(drop=True)
wti_df = wti_df.rename(columns = {0:'Date', 1:'Price of Barrel (usd)'}).sort_values(by='Date')
cpi_df = cpi_df.rename(columns = {0:'Date', 1:'Core CPI (index 1982-1984=100)'}).sort_values(by='Date')
unemp_df = unemp_df.rename(columns = {0:'Date', 1:'Unemployment (%)'}).sort_values(by='Date')
pce_df = pce_df.rename(columns = {0:'Date', 1:'Personal Consumption Expenditure (billions of usd)'}).sort_values(by='Date')

In [13]:
# Merge EIA data and WTI
data_frames = [supply_df,imports_df,production_df,wti_df]
df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['Date'],
                                            how='left'), data_frames)

In [14]:
# Merge FRED data
data_frames = [cpi_df, pce_df, unemp_df]
indicators_merged = reduce(lambda  left,right: pd.merge(left,right,on=['Date'],
                                            how='left'), data_frames)

In [15]:
# Creating new datetime columns to merge on
indicators_merged['Merge Date']= indicators_merged['Date'].dt.strftime('%m-%Y')

In [16]:
df_merged['Merge Date'] = df_merged['Date'].dt.strftime('%m-%Y')

In [17]:
# Merging and cleaning columns
final_df = pd.merge(df_merged, indicators_merged, how='left', on='Merge Date').fillna(method='ffill')
final_df = final_df[['Date_x', 'Merge Date', 'Personal Consumption Expenditure (billions of usd)','Core CPI (index 1982-1984=100)',
          'Unemployment (%)', 'Supply (thousand barrels per day)', 'Imports (thousand barrels per day)', 'Production (thousand barrels per day)', 
          'Price of Barrel (usd)']]
final_df = final_df.rename(columns = {"Date_x":"Date", "Merge Date":"Month"})
final_df.iloc[-1,:].values
final_df

,Date,Month,Personal Consumption Expenditure (billions of usd),Core CPI (index 1982-1984=100),Unemployment (%),Supply (thousand barrels per day),Imports (thousand barrels per day),Production (thousand barrels per day),Price of Barrel (usd)
0,1990-11-16,11-1990,3871.9,138.0,6.2,16588,5637,6910,31.50
1,1990-11-23,11-1990,3871.9,138.0,6.2,17019,5610,7440,30.69
2,1990-11-30,11-1990,3871.9,138.0,6.2,15686,4532,7235,32.32
3,1990-12-07,12-1990,3861.3,138.6,6.3,17753,5007,6996,27.72
4,1990-12-14,12-1990,3861.3,138.6,6.3,16901,5236,7474,26.39
5,1990-12-21,12-1990,3861.3,138.6,6.3,16669,5445,7245,27.56
6,1990-12-28,12-1990,3861.3,138.6,6.3,17953,4468,7559,27.21
7,1991-01-04,01-1991,3841.0,139.5,6.4,17319,5536,7481,26.38
8,1991-01-11,01-1991,3841.0,139.5,6.4,15968,4866,7475,27.55
9,1991-01-18,01-1991,3841.0,139.5,6.4,17171,5053,7461,26.85
10,1991-01-25,01-1991,3841.0,139.5,6.4,16699,5122,7219,24.08
11,1991-02-01,02-1991,3866.7,140.2,6.6,16246,6212,7477,21.41
12,1991-02-08,02-1991,3866.7,140.2,6.6,16801,5542,7463,21.30
13,1991-02-15,02-1991,3866.7,140.2,6.6,16067,5527,7427,22.12
14,1991-02-22,02-1991,3866.7,140.2,6.6,15627,4934,7415,19.38
15,1991-03-01,03-1991,3913.0,140.5,6.8,15414,4983,7404,18.73
16,1991-03-08,03-1991,3913.0,140.5,6.8,16997,5430,7394,19.86
17,1991-03-15,03-1991,3913.0,140.5,6.8,16982,4912,7412,19.89
18,1991-03-22,03-1991,3913.0,140.5,6.8,16914,5388,7385,20.30
19,1991-03-29,03-1991,3913.0,140.5,6.8,16408,5279,7383,19.58
20,1991-04-05,04-1991,3907.1,140.9,6.7,17481,5454,7356,19.63
21,1991-04-12,04-1991,3907.1,140.9,6.7,16344,6290,7334,20.89
22,1991-04-19,04-1991,3907.1,140.9,6.7,15888,4663,7370,21.48
23,1991-04-26,04-1991,3907.1,140.9,6.7,15799,5418,7346,21.19
24,1991-05-03,05-1991,3933.2,141.3,6.9,16054,5294,7295,21.23
25,1991-05-10,05-1991,3933.2,141.3,6.9,15995,6471,7303,21.69
26,1991-05-17,05-1991,3933.2,141.3,6.9,16306,5895,7280,20.95
27,1991-05-24,05-1991,3933.2,141.3,6.9,15273,6177,7336,21.04
28,1991-05-31,05-1991,3933.2,141.3,6.9,16357,6633,7323,21.21
29,1991-06-07,06-1991,3940.5,141.8,6.9,16226,6958,7301,20.63
...,...,...,...,...,...,...,...,...,...
1501,2019-08-23,08-2019,14682.4,264.180,3.7,22209,5928,12500,55.5
1502,2019-08-30,08-2019,14682.4,264.180,3.7,21621,6904,12400,55.21
1503,2019-09-06,09-2019,14707.8,264.682,3.5,21440,6725,12400,55.73
1504,2019-09-13,09-2019,14707.8,264.682,3.5,20262,7050,12400,56.16
1505,2019-09-20,09-2019,14707.8,264.682,3.5,21181,6378,12500,59.33
1506,2019-09-27,09-2019,14707.8,264.682,3.5,20751,6291,12400,56.9
1507,2019-10-04,10-2019,14740.6,264.987,3.6,21406,6224,12600,53.12
1508,2019-10-11,10-2019,14740.6,264.987,3.6,20905,6295,12600,53.27
1509,2019-10-18,10-2019,14740.6,264.987,3.6,21164,5857,12600,53.49
1510,2019-10-25,10-2019,14740.6,264.987,3.6,21597,6697,12600,55.2
1511,2019-11-01,11-2019,14786.2,265.501,3.5,21134,6077,12600,55.17
1512,2019-11-08,11-2019,14786.2,265.501,3.5,21500,5750,12800,56.69
1513,2019-11-15,11-2019,14786.2,265.501,3.5,21231,5972,12800,56.85
1514,2019-11-22,11-2019,14786.2,265.501,3.5,21106,6190,12900,56.9
1515,2019-11-29,11-2019,14786.2,265.501,3.5,21089,5989,12900,58.07
1516,2019-12-06,12-2019,14841.0,265.832,3.5,18359,6887,12800,57.64
1517,2019-12-13,12-2019,14841.0,265.832,3.5,21798,6579,12800,59.25
1518,2019-12-20,12-2019,14841.0,265.832,3.5,21312,6809,12900,60.75
1519,2019-12-27,12-2019,14841.0,265.832,3.5,19922,6352,12900,61.26
1520,2020-01-03,01-2020,14870.7,266.476,3.6,19351,6730,12900,61.62
1521,2020-01-10,01-2020,14870.7,266.476,3.6,19042,6552,13000,60.84
1522,2020-01-17,01-2020,14870.7,266.476,3.6,21504,6432,13000,58.29
1523,2020-01-24,01-2020,14870.7,266.476,3.6,19638,6660,13000,56.15
1524,2020-01-31,01-2020,14870.7,266.476,3.6,20835,6615,12900,52.69
1525,2020-02-07,02-2020,14870.7,267.070,3.5,20968,6978,13000,50.36
1526,2020-02-14,02-2020,14870.7,267.070,3.5,19590,6547,13000,50.83
1527,2020-02-21,02-2020,14870.7,267.070,3.5,19884,6217,13000,53.14
1528,2020-02-28,02-2020,14870.7,267.070,3.5,21272,6238,13100,48.36
1529,2020-03-06,03-2020,14870.7,267.070,3.5,21860,6412,13000,45.57
1530,2020-03-13,03-2020,14870.7,267.070,3.5,21477,6539,13100,32.39

In [18]:
# Staggering the price of WTI. This is so our independent variables are actually trained to predict next week's price.

PriceOfBarrel = final_df["Price of Barrel (usd)"]
StaggeredList=[]
count=1
while(count<len(PriceOfBarrel)):
    StaggeredList.append(PriceOfBarrel[count])
    count +=1
StaggeredList.append(0)
modeling_df = final_df.copy()
modeling_df ["Staggered Price of Barrel"] = StaggeredList
modeling_df = modeling_df.iloc[:-1]

modeling_df['Personal Consumption Expenditure (billions of usd)'] = pd.to_numeric(modeling_df['Personal Consumption Expenditure (billions of usd)'],errors='coerce')
modeling_df['Core CPI (index 1982-1984=100)'] = pd.to_numeric(modeling_df['Core CPI (index 1982-1984=100)'],errors='coerce')
modeling_df['Unemployment (%)'] = pd.to_numeric(modeling_df['Unemployment (%)'],errors='coerce')
modeling_df['Price of Barrel (usd)'] = pd.to_numeric(modeling_df['Price of Barrel (usd)'],errors='coerce')
modeling_df['Staggered Price of Barrel'] = pd.to_numeric(modeling_df['Staggered Price of Barrel'],errors='coerce')

modeling_df.to_csv("Data.csv")

In [19]:
# Linear Regression Model

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

model = LinearRegression()

X = modeling_df[["Personal Consumption Expenditure (billions of usd)",
              "Unemployment (%)",
              "Supply (thousand barrels per day)",
              "Imports (thousand barrels per day)",
              "Production (thousand barrels per day)"]]
y = modeling_df["Staggered Price of Barrel"].values.reshape(-1, 1)

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

model.fit(X_train, y_train)

training_score = model.score(X_train, y_train)
testing_score = model.score(X_test, y_test)
print(f"Training Score: {training_score}")
print(f"Testing Score: {testing_score}")

Training Score: 0.7450235396840565
Testing Score: 0.741516498992997

In [20]:
# Scaling data

from sklearn.preprocessing import StandardScaler

X_scaler = StandardScaler().fit(X_train)
y_scaler = StandardScaler().fit(y_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
y_train_scaled = y_scaler.transform(y_train)
y_test_scaled = y_scaler.transform(y_test)

In [21]:
# Decision Tree Model

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.tree import DecisionTreeRegressor

dtm = DecisionTreeRegressor(max_depth=4,
                           min_samples_split=5,
                            max_leaf_nodes=10)
dtm.fit(X_train_scaled, y_train_scaled)

training_score = dtm.score(X_train_scaled, y_train_scaled)
testing_score = dtm.score(X_test_scaled, y_test_scaled)
print(f"Training Score: {training_score}")
print(f"Testing Score: {testing_score}")

Training Score: 0.9341155232381579
Testing Score: 0.9376957666288445

In [22]:
# Random Forest Model

rfm = RandomForestRegressor(n_estimators=1000)

rfm.fit(X_train_scaled, y_train_scaled)

training_score = rfm.score(X_train_scaled, y_train_scaled)
testing_score = rfm.score(X_test_scaled, y_test_scaled)
print(f"Training Score: {training_score}")
print(f"Testing Score: {testing_score}")

C:\Users\Dan\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """

Training Score: 0.9983161374448516
Testing Score: 0.9900591739140779

In [23]:
y_predictions = rfm.predict(X_test_scaled)
mean_absolute_error(y_test_scaled, y_predictions)

0.07093704648968399

In [24]:
sorted(zip(rfm.feature_importances_, X), reverse=True)

[(0.8752030334383291, 'Personal Consumption Expenditure (billions of usd)'),
 (0.07816937164246804, 'Unemployment (%)'),
 (0.035873308120682346, 'Production (thousand barrels per day)'),
 (0.0054762332572665445, 'Supply (thousand barrels per day)'),
 (0.005278053541254029, 'Imports (thousand barrels per day)')]

In [26]:
most_recent_X = final_df.iloc[-1,:]

In [27]:
most_recent_X = X_scaler.transform([most_recent_X[X.columns].values])

In [28]:
price_next_week = rfm.predict(most_recent_X)

In [29]:
price_next_week = y_scaler.inverse_transform(price_next_week)[0].round(2)

In [30]:
from dateutil.relativedelta import relativedelta
most_recent_date = (final_df.iloc[-1,0]).date()
next_week_date = most_recent_date + relativedelta(weeks=+1)

In [31]:
most_recent_price = str(final_df.iloc[-1,8])

In [32]:
print("The price of oil (WTI) on Friday " + str(most_recent_date) + " was $" + str(most_recent_price) 
      +". Our model predicts that the price of oil on Friday " + str(next_week_date) + " will be $" + str(price_next_week) + ".")

The price of oil (WTI) on Friday 2020-03-13 was $32.39. Our model predicts that the price of oil on Friday 2020-03-20 will be $50.59.